version: "3.8"
services:
  app:
    build: 
      context: .
    container_name: pickside-frontend
    image: pickside-frontend-image
    ports: 
      - '3000:3000'
    # # might not work on windows
    # volumes:
    #   - ./src:/app
    #   - ./app/node_modules
    stdin_open: true
    tty: true