name: Deploy to EC2

on:
  pull_request:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: myenvironment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          npm ci
          npm run build
          tar -cvf build.tar ./build/

      - name: Copy via SSH and deploy on server
        uses: appleboy/scp-actions@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "build.tar"
          target: "/home/ubuntu"
