name: Deploy to EC2

on:
  pull_request:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_IP }} # Replace with your EC2 instance's public IP or hostname
          username: ${{ secrets.EC2_USERNAME }} # Replace with your EC2 instance's username
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }} # Store your SSH private key as a GitHub secret

          # Execute the deploy script on the EC2 instance
          script: |
            chmod +x deploy.sh
            ./deploy.sh
