name: Deploy to EC2

on:
  pull_request:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: myenvironment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          npm ci
          npm run build
          tar -cvf build.tar ./build/

      - name: Copy via SSH and deploy on server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SCP_PORT }}
          source: "build.tar"
          target: "/home/ubuntu"
