name: React Continuous Integration

on:
  pull_request:
    branches: [release]

jobs:
  test_pull_request:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
