name: Pickside App Deploy

on: push

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - run: npm ci
      - run: npm run build
      #- run: npm run test

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/pickside/
          remote_host: ${{ secrets.SSH_HOST }}.compute-1.amazonaws.com
          remote_user: ${{ secrets.USER_NAME }}
          remote_key: '${{ secrets.SSH_PRIVATE_KEY }}'
